[workspace]
members = ["shallowclone", "shallowclone-derive"]
resolver = "2"

[workspace.dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro-error = "1.0"
